jinahub/indexers/searcher/AnnoySearcher/__init__.py
jinahub/indexers/searcher/AnnoySearcher/tests/test_annoyindexer.py
jinahub/indexers/searcher/FaissSearcher/__init__.py
jinahub/indexers/searcher/FaissSearcher/tests/test_faissindexer.py
jinahub/indexers/searcher/HnswlibSearcher/__init__.py
jinahub/indexers/searcher/HnswlibSearcher/tests/test_hnswlibsearcher.py
jinahub/indexers/searcher/NumpySearcher/__init__.py
jinahub/indexers/searcher/NumpySearcher/tests/test_query.py
scripts/tests.sh
tests/integration/lmdb_dump_reload/test_dump_lmdb.py
tests/integration/psql_dump_reload/test_dump_psql.py

this is a copy-paste of https://github.com/jina-ai/executor-indexers/pull/74
the `test.sh` needs improvements as well

feat: unify scores

---

scripts/push.sh

fix: empty push

---

jinahub/indexers/storage/LMDBStorage/README.md
jinahub/indexers/storage/PostgreSQLStorage/README.md
jinahub/indexers/storage/RedisStorage/README.md

docs: add section for localhost problem on macos

---

jinahub/indexers/storage/LMDBStorage/__init__.py
jinahub/indexers/storage/LMDBStorage/tests/test_lmdb.py
jinahub/indexers/storage/PostgreSQLStorage/__init__.py
jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
jinahub/indexers/storage/PostgreSQLStorage/tests/test_postgres_dbms.py
jinahub/indexers/storage/RedisStorage/__init__.py
jinahub/indexers/storage/RedisStorage/tests/test_unit.py

closes https://github.com/jina-ai/internal-tasks/issues/135

feat: add return_embeddings parameter to storage executors

---

.github/workflows/cd.yml
jinahub/segmenters/YoloV5Segmenter/Dockerfile

fix: yolov5 push to hub 

---

jinahub/indexers/searcher/FaissSearcher/__init__.py

Update logger message from 'AnnoyIndexer' to 'FaissIndexer'.

Update logger message

---

setup.py

- fix setup.py
- add init.py where missing (required in order for modules to be installed)
Classes will be available as:
```
from jinahub.indexers.SimpleIndexer import SimpleIndexer
from jinahub.encoders.image.ImageTorchEncoder.torch_encoder import ImageTorchEncoder
```

fix: packaging

---

jinahub/encoders/image/CLIPImageEncoder/requirements.txt

fix: add missing package to req

---

jinahub/crafters/ImageNormalizer/README.md
jinahub/encoders/image/BigTransferEncoder/README.md
jinahub/encoders/image/CustomImageTorchEncoder/README.md
jinahub/rankers/CatboostRanker/tests/unit/test_catboost.py
jinahub/rankers/MinRanker/README.md
jinahub/rankers/MinRanker/tests/integration/test_flow.py

replace `overrides_with`&`overrides_metas` with `uses_with`&`uses_metas` in Jinahub files

replace overrides_with&overrides_metas with uses_with&uses_metas

---

jinahub/crafters/ImageNormalizer/Dockerfile
jinahub/crafters/ImageNormalizer/normalizer.py
jinahub/crafters/ImageNormalizer/tests/unit/test_normalizer.py

as a user the images may be in chunks level, so we better support this

fix: add traversal paths

---

jinahub/indexers/storage/PostgreSQLStorage/Dockerfile
jinahub/indexers/storage/PostgreSQLStorage/postgres_indexer.py
jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
jinahub/indexers/storage/PostgreSQLStorage/tests/test_postgres_dbms.py
tests/integration/psql_dump_reload/flow_query.yml
tests/integration/psql_dump_reload/flow_storage.yml
tests/integration/psql_dump_reload/test_dump_psql.py
tests/requirements.txt

This adds a dump performance improvement. Beware, that this is not yet finished, since it always expects embedding of `float32`.

feat: improved dump performance

---

jinahub/encoders/image/BigTransferEncoder/big_transfer.py

docs: update BiT docstrings

---

jinahub/encoders/image/BigTransferEncoder/big_transfer.py
jinahub/encoders/image/BigTransferEncoder/tests/integration/test_integration.py
jinahub/encoders/image/BigTransferEncoder/tests/unit/test_big_transfer.py

chore: update the model path for BiT

---

jinahub/encoders/image/ImageTFEncoder/image_tf_encoder.py

update docstrings for ImageTFEncoder

docs: update docstrings for ImageTFEncoder

---

tests/integration/psql_dump_reload/flow_query.yml

This setting did not had any effect.

refactor: removed unused argument

---

jinahub/segmenters/VADSpeechSegmenter/README.md

docs: revisit VADSpeechSegmenter readme

---

jinahub/segmenters/VADSpeechSegmenter/README.md

docs: VADSpeechSegmenter readme

---

README.md

docs: note on setup py and compounds

---

jinahub/indexers/storage/PostgreSQLStorage/postgres_indexer.py
jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
jinahub/indexers/storage/PostgreSQLStorage/tests/docker_args.txt
jinahub/indexers/storage/PostgreSQLStorage/tests/test_postgres_dbms.py

Added versioning to the PSQLIndexer. This prevents data corruption when we change the table schema.

feat: psql schema has versioning

---

jinahub/encoders/image/CustomImageTorchEncoder/README.md
jinahub/encoders/image/CustomImageTorchEncoder/custom_image_torch_encoder.py

Added parameter details to README for Custom Image Torch Encoder

docs: add parameter details for custom image torch encoder

---

scripts/get-all-test-paths.sh

This branch fixes the bug that the CI does not detect changes in the test folders

ci: notice changes in test folders

---

jinahub/indexers/searcher/FaissSearcher/Dockerfile.gpu
jinahub/indexers/searcher/FaissSearcher/config.yml
jinahub/indexers/searcher/FaissSearcher/faiss_searcher.py
jinahub/indexers/searcher/FaissSearcher/gpu_requirements.txt
jinahub/indexers/searcher/FaissSearcher/tests/integration/test_save_load.py
jinahub/indexers/searcher/FaissSearcher/tests/integration/test_snapshot.py
jinahub/indexers/searcher/FaissSearcher/tests/unit/test_faisssearcher.py

The preliminary is https://github.com/jina-ai/executors/pull/96

feat(faiss): supporting soft delete and incremental indexing

---

jinahub/indexers/storage/MongoDBStorage/mongo_handler.py

This PR changes embedding to a list of python float from list of NumPy float

fix(MongoDBStorage): fix embedding datatype to float

---

jinahub/indexers/searcher/FaissSearcher/config.yml
jinahub/indexers/searcher/FaissSearcher/faiss_searcher.py
jinahub/indexers/searcher/FaissSearcher/tests/unit/test_faisssearcher.py
jinahub/indexers/searcher/compound/FaissPostgresSearcher/config.yml
jinahub/indexers/searcher/compound/FaissPostgresSearcher/faisspsql.py
jinahub/indexers/searcher/compound/FaissPostgresSearcher/requirements.txt
jinahub/indexers/storage/PostgreSQLStorage/postgres_indexer.py
jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
tests/integration/psql_import/test_import_psql.py

Add an integration test to show off sync with deltas in PSQLFaissSearcher

test: add integration test for sync with delta

---

jinahub/encoders/text/TransformerTorchEncoder/transform_encoder.py

fix: move executor constructor docstring under constructor

fix: move executor constructor docstring under constructor

---

jinahub/encoders/text/TransformerTorchEncoder/README.md
jinahub/encoders/text/TransformerTorchEncoder/transform_encoder.py

polish readme for transformtorchencoder

refactor: polish readme for transformer torch encoder

---

jinahub/indexers/merger/MatchMerger/manifest.yml
tests/requirements.txt

remove unused fields in `manifest.yml`

chore: remove unused fields in manifest.yml

---

jinahub/encoders/image/CLIPImageEncoder/README.md
jinahub/encoders/image/CLIPImageEncoder/tests/unit/test_clip.py

1. polish readme
2. add more edge cases in tests.

refactor: clean up clip image encoder

---

jinahub/indexers/searcher/FaissSearcher/README.md

the task is to polish up the readme for executor. I did not add too much content, only kept it compact with some reorganize.

refactor: update faiss readme

---

jinahub/crafters/ImageNormalizer/normalizer.py
jinahub/crafters/ImageNormalizer/tests/unit/test_normalizer.py
jinahub/rankers/DPRReaderRanker/dpr_reader.py
jinahub/rankers/DPRReaderRanker/tests/unit/test_ranker.py
jinahub/rankers/SimpleRanker/simpleranker.py
jinahub/rankers/SimpleRanker/tests/unit/test_ranker.py
jinahub/segmenters/Sentencizer/sentencizer.py
jinahub/segmenters/TorchObjectDetectionSegmenter/tests/unit/test_exec.py
jinahub/segmenters/TorchObjectDetectionSegmenter/torch_object_detection_segmenter.py
jinahub/segmenters/YoloV5Segmenter/tests/unit/test_exec.py
jinahub/segmenters/YoloV5Segmenter/yolov5_segmenter.py

chore: rename args

---

jinahub/encoders/audio/VGGISHAudioEncoder/README.md
jinahub/encoders/audio/VGGISHAudioEncoder/tests/unit/test_exec.py

1. simplification of readme
2. more edge test cases.
Part of #84

refactor: add more edge tests for VGGish audio encoder

---

jinahub/encoders/video/VideoTorchEncoder/README.md
jinahub/encoders/video/VideoTorchEncoder/gpu_requirements.txt
jinahub/encoders/video/VideoTorchEncoder/requirements.txt
jinahub/encoders/video/VideoTorchEncoder/tests/unit/test_video_torch_encoder.py
jinahub/encoders/video/VideoTorchEncoder/video_torch_encoder.py

1. add more edge tests
2. refactor jina commons with `batch` function

refactor: refactor video encoder

---

.github/workflows/cd.yml
jinahub/indexers/DocCache/README.md
jinahub/indexers/searcher/AnnoySearcher/README.md
jinahub/indexers/searcher/FaissSearcher/README.md
jinahub/indexers/searcher/HnswlibSearcher/Dockerfile
jinahub/indexers/searcher/HnswlibSearcher/README.md
jinahub/indexers/searcher/HnswlibSearcher/config.yml
jinahub/indexers/searcher/compound/FaissLMDBSearcher/README.md
jinahub/indexers/searcher/compound/FaissPostgresIndexer/README.md
jinahub/indexers/storage/LMDBStorage/README.md
jinahub/indexers/storage/MongoDBStorage/README.md
jinahub/indexers/storage/PostgreSQLStorage/README.md
jinahub/indexers/storage/RedisStorage/README.md
jinahub/rankers/CatboostRanker/README.md
jinahub/rankers/DPRReaderRanker/README.md
jinahub/rankers/LightGBMRanker/README.md
jinahub/rankers/SimpleRanker/README.md
jinahub/segmenters/PDFSegmenter/README.md
jinahub/segmenters/Sentencizer/README.md
jinahub/segmenters/VADSpeechSegmenter/README.md
jinahub/segmenters/YoloV5Segmenter/README.md
scripts/push.sh
scripts/push_gpu.sh

Adds versioning. Part 1, since CI is breaking a lot.
Then do https://github.com/jina-ai/executors/pull/243

ci: add versioning 1/2

---

jinahub/crafters/ImageNormalizer/README.md
jinahub/encoders/audio/AudioCLIPEncoder/README.md
jinahub/encoders/audio/VGGISHAudioEncoder/README.md
jinahub/encoders/image/AudioCLIPImageEncoder/README.md
jinahub/encoders/image/BigTransferEncoder/README.md
jinahub/encoders/image/CLIPImageEncoder/README.md
jinahub/encoders/image/CustomImageTorchEncoder/README.md
jinahub/encoders/image/ImagePaddlehubEncoder/README.md
jinahub/encoders/image/ImageTFEncoder/README.md
jinahub/encoders/image/TimmImageEncoder/README.md
jinahub/encoders/text/AudioCLIPTextEncoder/README.md
jinahub/encoders/text/DPRTextEncoder/README.md
jinahub/encoders/text/FlairTextEncoder/README.md
jinahub/encoders/text/LaserEncoder/README.md
jinahub/encoders/text/SpacyTextEncoder/README.md
jinahub/encoders/text/TFIDFTextEncoder/README.md
jinahub/encoders/text/TextPaddleEncoder/README.md
jinahub/encoders/text/TransformerSentenceEncoder/README.md
jinahub/encoders/text/TransformerTFTextEncoder/README.md
jinahub/encoders/video/VideoTorchEncoder/README.md

To be done after https://github.com/jina-ai/executors/pull/235

ci: add vesions for other executors

---

jinahub/indexers/searcher/compound/FaissPostgresIndexer/faisspsql.py
tests/integration/psql_import/test_import_psql.py

Show how to use snapshot or just delta in the benchmark.

test: show how to use snapshot or just delta

---

jinahub/indexers/searcher/FaissSearcher/faiss_searcher.py
jinahub/indexers/searcher/compound/FaissPostgresIndexer/README.md
jinahub/indexers/searcher/compound/FaissPostgresIndexer/faisspsql.py
jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
tests/integration/psql_import/test_import_psql.py

Refactor usage of startup args, to be easier and adapt to scenario.

refactor: specify startup arg

---

jinahub/indexers/searcher/AnnoySearcher/README.md
jinahub/indexers/searcher/AnnoySearcher/requirements.txt
jinahub/indexers/storage/LMDBStorage/README.md
jinahub/indexers/storage/LMDBStorage/requirements.txt
jinahub/indexers/storage/PostgreSQLStorage/README.md
jinahub/indexers/storage/PostgreSQLStorage/requirements.txt

Goals:
Address this issue https://github.com/jina-ai/jina/issues/3990 
- ...
- ...

fix: jina common

---

jinahub/encoders/audio/AudioCLIPEncoder/README.md
jinahub/encoders/image/AudioCLIPImageEncoder/README.md

docs: version update

---

jinahub/encoders/audio/AudioCLIPEncoder/README.md
jinahub/encoders/audio/AudioCLIPEncoder/executor/audio_clip_encoder.py
jinahub/encoders/audio/AudioCLIPEncoder/tests/unit/test_exec.py

Goals:
- Fix the AudioCLIPEncoder

fix: minor fix

---

jinahub/encoders/text/AudioCLIPTextEncoder/README.md
jinahub/encoders/text/AudioCLIPTextEncoder/executor/audio_clip/model/audioclip.py
jinahub/encoders/text/AudioCLIPTextEncoder/executor/audio_clip/utils/simple_tokenizer.py
jinahub/encoders/text/AudioCLIPTextEncoder/executor/audioclip_text.py

Fix several wrong/confusing error messages regarding the loading of a pretrained model

fix: ix model loading in audio clip text encoder

---

jinahub/indexers/compound/FaissPostgresIndexer/faisspsql.py

refactor: change pea_id to shard_id

---

jinahub/segmenters/Sentencizer/README.md
jinahub/segmenters/Sentencizer/sentencizer.py
jinahub/segmenters/Sentencizer/tests/integration/test_exec.py
jinahub/segmenters/Sentencizer/tests/unit/test_exec.py

Goals:
- upgrade Sentencizer to 3.0
- ...

feat: upgrade sentencizer to 3.0
